[electrum] make contrib/sign_packages support multi digits in version numbers
Summary: And exit with an error message when the version string is not detected, instead of producing a sha256_checksums.txt number without a version number.

Test Plan:
```
$ touch dist/ElectrumABC-1.1.1.tar.gz
$ contrib/sign_packages
Detected version number: 1.1.1
Checksum file: sha256_checksums-1.1.1.txt
Password:
Signature file: sha256_checksums-1.1.1.txt.sig
$ rm dist/ElectrumABC-1.1.1.tar.gz
$ touch dist/ElectrumABC-1.1.10.tar.gz
$ contrib/sign_packages
Detected version number: 1.1.10
Checksum file: sha256_checksums-1.1.10.txt
Password:
Signature file: sha256_checksums-1.1.10.txt.sig
$ rm dist/ElectrumABC-1.1.10.tar.gz
$ touch dist/ElectrumABC-1337.42.666.tar.gz
$ contrib/sign_packages
Detected version number: 1337.42.666
Checksum file: sha256_checksums-1337.42.666.txt
Password:
Signature file: sha256_checksums-1337.42.666.txt.sig
$ rm dist/ElectrumABC-1337.42.666.tar.gz
$ touch dist/ElectrumABC-1.1.1.1.tar.gz
$ contrib/sign_packages
Error: could not find release version number.
```

Reviewers: #bitcoin_abc, Fabien

Reviewed By: #bitcoin_abc, Fabien

Differential Revision: https://reviews.bitcoinabc.org/D14978